### PR TITLE
Remove pytest from install_requires

### PR DESCRIPTION
**Pull request by r-imai-quantum**
When you run `pip install openfermionpyscf`, `pytest` is installed together since it is in `setup_requires` field of `setup.py`.
Only developers need `pytest`, so it is good to remove `pytest` from `setup_requires` field.

### CODE REVIEW

**Comment by r-imai-quantum** [comment]
CI failed becauce of wrong settings in ci.yml.

**Comment by ncrubin** [comment]
Hi @r-imai-quantum Thank you for this fix. I think the better fix would be to actually make a dev_tools/pip-list instead of just removing pytest.  Could. you do that with this PR?

**Comment by r-imai-quantum** [comment]
Thank you for your comments.
Please let me confirm one thing.
Does dev_tools/pip-list you mentioned mean a list of dependencies to execute tests?

**Comment by ncrubin** [comment]
That is correct. For this it will be pyscf, pytest, openfermion.

**Comment by r-imai-quantum** [comment]
Updated. Could you check again? @ncrubin

**Review by ncrubin — APPROVED** [review]
LGTM

**Pull request merged**
