### PR TITLE
Travis CI config

### PR DESCRIPTION
**Pull request by sunqm**
Travis CI config file was added.

### CODE REVIEW

**Comment by babbush** [comment]
We usually test in python 2.7, 3.4, 3.5 and 3.6. @Strilanc can you help us configure travis based on this PR?

**Comment by babbush** [comment]
@sunqm let me know when you are going to work on this repo imminently. We can then prioritize setting up travis (which is going to be somewhat of a battle I fear).

**Comment by sunqm** [comment]
@babbush Don't worry. No rush on me.

I'm figuring that if I made changes on my fork, it may mess up the PR.  Will it be more convenient if I close this PR now and wait for you guys deciding how to set up travis?

**Comment by babbush** [comment]
It is fine to leave it open actually. Feel free to mess it up ;-)

But you are also welcome to close it. Makes no difference to me.

**Pull request closed without merging**
