### PR TITLE
Bump version to 0.4

### PR DESCRIPTION
**Pull request by kevinsung**
Necessary to sync the library with PySCF (see #41 ).

### CODE REVIEW

**Comment by babbush** [comment]
How is this necessary to sync with PySCF?

**Comment by kevinsung** [comment]
Otherwise the package suffers from the bug #40

**Comment by sunqm** [comment]
openfermionpyscf 0.3 on pypi suffers from bug #40 . Hope the 0.4 version will be uploaded to pypi soon.

**Comment by kevinsung** [comment]
@babbush do you have any issues with this PR?

**Comment by kevinsung** [comment]
This is quite urgent so I am going to exercise my administrator privileges here.

**Comment by kevinsung** [comment]
@sunqm Version 0.4 has been uploaded to PyPI. Sorry for the delay.

**Comment by sunqm** [comment]
Great, Thanks!

On Fri, Mar 15, 2019 at 11:54:34AM -0700, Kevin J. Sung wrote:
> @sunqm Version 0.4 has been uploaded to PyPI. Sorry for the delay.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.*
> 

-- 
Dr. Qiming Sun
Principal Researcher, Tencent Quantum Laboratory

**Pull request merged**
